package com.healthcompanion.api;
import com.healthcompanion.domain.*; import com.healthcompanion.repository.UserRepository; import com.healthcompanion.security.JwtService; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.http.*; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException;
@RestController @RequestMapping("/api/auth") public class AuthController {
 private final UserRepository users; private final PasswordEncoder passwords; private final JwtService jwt; public AuthController(UserRepository u,PasswordEncoder p,JwtService j){users=u;passwords=p;jwt=j;}
 @PostMapping("/register") @ResponseStatus(HttpStatus.CREATED) public AuthResponse register(@Valid @RequestBody RegisterRequest r){if(users.findByEmailIgnoreCase(r.email()).isPresent())throw new ResponseStatusException(HttpStatus.CONFLICT,"Email already registered"); if(!r.password().equals(r.confirmPassword()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Passwords do not match"); var u=new User();u.firstName=r.firstName();u.lastName=r.lastName();u.email=r.email().toLowerCase();u.phone=r.phone();u.passwordHash=passwords.encode(r.password());u.role=Role.PATIENT;u=users.save(u);return response(u);}
 @PostMapping("/login") public AuthResponse login(@Valid @RequestBody LoginRequest r){var u=users.findByEmailIgnoreCase(r.email()).filter(x->passwords.matches(r.password(),x.passwordHash)).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Invalid credentials"));return response(u);}
 private AuthResponse response(User u){return new AuthResponse(jwt.issue(u),u.id,u.firstName,u.lastName,u.email,u.role);}
 public record RegisterRequest(@NotBlank String firstName,@NotBlank String lastName,@Email String email,String phone,@Size(min=8) String password,@NotBlank String confirmPassword){} public record LoginRequest(@Email String email,@NotBlank String password){} public record AuthResponse(String token,Long id,String firstName,String lastName,String email,Role role){}
}
