import type { PropsWithChildren } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

export const colors = { primary: '#0f766e', background: '#f8f7f2', ink: '#183634', muted: '#647573', card: '#ffffff', danger: '#c54d4d' };
export function Screen({ children }: PropsWithChildren) { return <ScrollView contentContainerStyle={styles.screen}>{children}</ScrollView>; }
export function Title({ children }: PropsWithChildren) { return <Text style={styles.title}>{children}</Text>; }
export function Card({ children }: PropsWithChildren) { return <View style={styles.card}>{children}</View>; }
export function Button({ title, onPress, disabled, tone = 'primary' }: { title: string; onPress: () => void; disabled?: boolean; tone?: 'primary' | 'outline' | 'danger' }) { return <Pressable accessibilityRole="button" accessibilityLabel={title} disabled={disabled} onPress={onPress} style={[styles.button, tone === 'outline' && styles.outline, tone === 'danger' && styles.danger, disabled && styles.disabled]}><Text style={[styles.buttonText, tone === 'outline' && styles.outlineText]}>{title}</Text></Pressable>; }
export function Field({ label, value, onChangeText, secureTextEntry = false, keyboardType = 'default' }: { label: string; value: string; onChangeText: (value: string) => void; secureTextEntry?: boolean; keyboardType?: 'default' | 'email-address' | 'phone-pad' }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput accessibilityLabel={label} autoCapitalize="none" autoCorrect={false} value={value} onChangeText={onChangeText} secureTextEntry={secureTextEntry} keyboardType={keyboardType} style={styles.input} /></View>; }
export function ErrorText({ message }: { message?: string }) { return message ? <Text accessibilityRole="alert" style={styles.error}>{message}</Text> : null; }
const styles = StyleSheet.create({ screen: { flexGrow: 1, backgroundColor: colors.background, padding: 20, gap: 14 }, title: { fontSize: 28, fontWeight: '800', color: colors.ink, marginTop: 24 }, card: { backgroundColor: colors.card, borderColor: '#e2ebe5', borderWidth: 1, borderRadius: 14, padding: 16, gap: 10 }, button: { backgroundColor: colors.primary, minHeight: 46, justifyContent: 'center', alignItems: 'center', borderRadius: 12, paddingHorizontal: 16 }, outline: { backgroundColor: 'transparent', borderColor: colors.primary, borderWidth: 1 }, danger: { backgroundColor: colors.danger }, disabled: { opacity: .5 }, buttonText: { color: 'white', fontWeight: '700', fontSize: 16 }, outlineText: { color: colors.primary }, field: { gap: 6 }, label: { color: colors.ink, fontWeight: '700' }, input: { backgroundColor: '#fff', borderColor: '#ccd9d5', borderWidth: 1, borderRadius: 12, minHeight: 46, paddingHorizontal: 12, color: colors.ink }, error: { color: colors.danger, fontWeight: '600' } });
